### ISSUE TITLE
Feature Request: support statusline.nvim

### ISSUE THREAD

**Issue by emmett2020** [dustypomerleau/tol.nvim#1]
Thx for the awesome theme, it's so beautiful. Could you please add the support for statusline.nvim which is also a popular nvim plugin like lualine.nvim?

**Comment by dustypomerleau** [comment]
Could you link to the repo for the plugin?

**Comment by emmett2020** [comment]
sorry, I made a mistake with the plugin, what I mentioned statusline.nvim just is lualine.nvim
